name: Test Solutions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Solutions
        run: |
          bash -c 'for f in `find 2021 -type d -depth 1 -iname "day*"`; do (cd $f; python -m unittest) || exit 1; done'
