name: Test Solutions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Test Solutions
        run: |
          for f in `find 2021 -type d -iname "day*"`; do (pushd $f; python3.9 -m unittest) || exit 1; done
